
.PHONY: all
all: \
	python.inv \
	joblib.inv \
	torch.inv \
	psutil.inv \
	pandas.inv \
	numpy.inv \


python.inv:
	wget -4 https://docs.python.org/3.8/objects.inv -O python.inv
joblib.inv:
	wget -4 https://joblib.readthedocs.io/en/latest/objects.inv -O joblib.inv
torch.inv:
	wget -4 https://pytorch.org/docs/stable/objects.inv -O torch.inv
psutil.inv:
	wget -4 https://psutil.readthedocs.io/en/latest/objects.inv -O psutil.inv
pandas.inv:
	wget -4 https://pandas.pydata.org/docs/objects.inv -O pandas.inv
numpy.inv:
	wget -4 https://numpy.org/doc/stable/objects.inv -O numpy.inv

