[ysjsd]
name = "ylsjs_cluster"
description = "No description"
ysjs_port = "8080"
var_directory = "/mnt/f/home/Desktop/labw_utils/var"
config_file_path = "/mnt/f/home/Desktop/labw_utils/config.toml"

[deps]
labw_utils = "0.1.13"
ysjsd = "0.1.0"
flask = "2.2.3"
python = "3.8.15"
